version: '3.6'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "256m"
        max-file: "10"
